// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CacheRepository is an autogenerated mock type for the CacheRepository type
type CacheRepository struct {
	mock.Mock
}

// IsSeen provides a mock function with given fields: ctx, hhID
func (_m *CacheRepository) IsSeen(ctx context.Context, hhID string) (bool, error) {
	ret := _m.Called(ctx, hhID)

	if len(ret) == 0 {
		panic("no return value specified for IsSeen")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, hhID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, hhID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hhID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetSeen provides a mock function with given fields: ctx, hhID
func (_m *CacheRepository) SetSeen(ctx context.Context, hhID string) error {
	ret := _m.Called(ctx, hhID)

	if len(ret) == 0 {
		panic("no return value specified for SetSeen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, hhID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCacheRepository creates a new instance of CacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheRepository {
	mock := &CacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
