// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Royal17x/hireradar/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// VacancyRepository is an autogenerated mock type for the VacancyRepository type
type VacancyRepository struct {
	mock.Mock
}

// Exists provides a mock function with given fields: ctx, hhID
func (_m *VacancyRepository) Exists(ctx context.Context, hhID string) (bool, error) {
	ret := _m.Called(ctx, hhID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, hhID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, hhID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, hhID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx
func (_m *VacancyRepository) GetAll(ctx context.Context) ([]domain.Vacancy, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Vacancy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Vacancy, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Vacancy); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Vacancy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, vacancy
func (_m *VacancyRepository) Save(ctx context.Context, vacancy *domain.Vacancy) error {
	ret := _m.Called(ctx, vacancy)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Vacancy) error); ok {
		r0 = rf(ctx, vacancy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewVacancyRepository creates a new instance of VacancyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVacancyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VacancyRepository {
	mock := &VacancyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
