// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Royal17x/hireradar/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// VacancyFetcher is an autogenerated mock type for the VacancyFetcher type
type VacancyFetcher struct {
	mock.Mock
}

// FetchVacancies provides a mock function with given fields: ctx, query
func (_m *VacancyFetcher) FetchVacancies(ctx context.Context, query string) ([]domain.Vacancy, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for FetchVacancies")
	}

	var r0 []domain.Vacancy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.Vacancy, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.Vacancy); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Vacancy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVacancyFetcher creates a new instance of VacancyFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVacancyFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *VacancyFetcher {
	mock := &VacancyFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
